'use client';

import { ChevronLeft, ChevronRight, FileUp, LayoutDashboard, Search, ShieldCheck, Sparkles, X } from 'lucide-react';
import { FormEvent, useEffect, useState } from 'react';
import { approveUpload, Candidate, CandidateFilters, getCandidate, getCandidates, getMetrics, getStaticRecommendations, getUploadStatus, Metrics, rejectUpload, Recommendation, uploadCv } from '../lib/api';

const emptyMetrics: Metrics = { total_candidates: 0, screened_candidates: 0, industries: {}, positions: {}, locations: {}, screening_statuses: {}, experience_distribution: {}, salary_distribution: {}, recent_candidates: [] };
const defaultFilters: CandidateFilters = { page: 1, page_size: 20 };

export default function Home() {
  const [query, setQuery] = useState('');
  const [recommendationOpen, setRecommendationOpen] = useState(false);
  const [filters, setFilters] = useState<CandidateFilters>(defaultFilters);
  const [results, setResults] = useState<Candidate[]>([]);
  const [recommendations, setRecommendations] = useState<Recommendation[]>([]);
  const [metrics, setMetrics] = useState<Metrics>(emptyMetrics);
  const [total, setTotal] = useState(0);
  const [selected, setSelected] = useState<Candidate | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [uploadMessage, setUploadMessage] = useState('');
  const [uploadId, setUploadId] = useState('');
  const [hydrated, setHydrated] = useState(false);

  async function loadCandidates(nextFilters = filters) {
    setLoading(true); setError('');
    try { const response = await getCandidates(nextFilters); setResults(response.items); setTotal(response.total); }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load candidates.'); }
    finally { setLoading(false); }
  }
  useEffect(() => { setHydrated(true); getMetrics().then(setMetrics).catch(reason => setError(reason instanceof Error ? reason.message : 'Unable to load dashboard metrics.')); loadCandidates(); }, []);
  async function submitSearch(event: FormEvent) { event.preventDefault(); setRecommendations([]); const next = { ...filters, q: query, page: 1 }; setFilters(next); await loadCandidates(next); }
  async function submitRecommendation(event: FormEvent) { event.preventDefault(); setLoading(true); setError(''); try { const response = await getStaticRecommendations(10); setRecommendations(response.results); setResults(response.results.map(item => ({ ...item.candidate, suitability_score: item.overall_score, score_reasons: item.matched_criteria, score_gaps: item.concerns }))); setTotal(response.results.length); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to generate static ranking.'); } finally { setLoading(false); } }
  function updateFilter(key: keyof CandidateFilters, value: string) { const next = { ...filters, [key]: value, page: 1 }; setRecommendations([]); setFilters(next); loadCandidates(next); }
  async function openCandidate(id: string) { setError(''); try { setSelected(await getCandidate(id)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load candidate.'); } }
  async function handleUpload(file?: File) { if (!file) return; setUploadMessage('Uploading CV...'); try { const response = await uploadCv(file); setUploadId(response.upload_id); setUploadMessage('Uploading → Extracting → Identifying candidate...'); let status = await getUploadStatus(response.upload_id); for (let attempt = 0; attempt < 20 && !['ready_for_review', 'extraction_failed'].includes(status.status); attempt += 1) { await new Promise(resolve => setTimeout(resolve, 500)); status = await getUploadStatus(response.upload_id); } setUploadMessage(status.status === 'ready_for_review' ? `CV ready for review (${status.extraction_method}, quality ${status.extraction_quality ?? 0}).` : status.error || 'Unable to extract readable text from this CV.'); } catch (reason) { setUploadMessage(reason instanceof Error ? reason.message : 'Upload failed.'); } }
  async function decideUpload(action: 'approve' | 'reject') { if (!uploadId) return; try { const result = action === 'approve' ? await approveUpload(uploadId) : await rejectUpload(uploadId); setUploadMessage(`CV proposal ${result.status}.`); setUploadId(''); if (action === 'approve') { const [nextMetrics] = await Promise.all([getMetrics(), loadCandidates({ ...filters, page: 1 })]); setMetrics(nextMetrics); } } catch (reason) { setUploadMessage(reason instanceof Error ? reason.message : 'Unable to update CV proposal.'); } }
  const topIndustries = Object.entries(metrics.industries);
  const page = filters.page || 1;
  return <div className="shell">
    <aside className="sidebar"><div className="brand">talent<span>/</span>signal</div><nav className="nav"><button className="active"><LayoutDashboard size={16} /> Dashboard</button><button className={recommendationOpen ? 'selected' : ''} onClick={() => setRecommendationOpen(value => !value)}><Sparkles size={16} /> Best matches</button><label className="nav button"><FileUp size={16} /> CV intake<input hidden type="file" accept=".pdf,.docx,.txt" onChange={event => handleUpload(event.target.files?.[0])} /></label></nav><div className="side-foot">WORKSPACE<strong>Northstar Recruitment</strong><br />Single tenant MVP</div></aside>
    <main className="main"><header className="top"><div><div className="eyebrow">Recruiter workspace / Overview</div><h1>Candidate intelligence</h1><p>Find the people who move the brief forward.</p></div><div className="user"><span>Alex Morgan<br /><small style={{ color: 'var(--muted)' }}>Recruiter</small></span><span className="avatar">AM</span></div></header>
      <section className="metrics"><Metric label="Total candidates" value={metrics.total_candidates.toLocaleString()} accent="Master dataset" /><Metric label="Screened" value={metrics.screened_candidates.toLocaleString()} accent="With screening outcome" /><Metric label="Industries" value={Object.keys(metrics.industries).length.toString()} accent="Across the workspace" /><Metric label="Locations" value={Object.keys(metrics.locations).length.toString()} accent="Candidate locations" /></section>
      <section className="search-panel"><label className="search-label" htmlFor="search">SEARCH CANDIDATES</label><form className="search-row" onSubmit={submitSearch}><Search size={19} color="#12645b" style={{ position: 'absolute', margin: '14px' }} /><input id="search" className="search-input" style={{ paddingLeft: 44 }} value={query} onChange={event => setQuery(event.target.value)} placeholder="Search by name, role, skill, city..." /><button className="search-button" type="submit">{loading && !recommendations.length ? 'Searching...' : 'Search'}</button></form><div className="filters"><select aria-label="Position" value={filters.position || ''} onChange={event => updateFilter('position', event.target.value)}><option value="">All positions</option>{Object.keys(metrics.positions).map(item => <option key={item}>{item}</option>)}</select><select aria-label="Industry" value={filters.industry || ''} onChange={event => updateFilter('industry', event.target.value)}><option value="">All industries</option>{Object.keys(metrics.industries).map(item => <option key={item}>{item}</option>)}</select><select aria-label="Experience" value={filters.min_experience || ''} onChange={event => updateFilter('min_experience', event.target.value)}><option value="">Any experience</option><option value="3">3+ years</option><option value="5">5+ years</option><option value="10">10+ years</option></select><select aria-label="Screening" value={filters.screening || ''} onChange={event => updateFilter('screening', event.target.value)}><option value="">Any screening status</option>{Object.keys(metrics.screening_statuses).map(item => <option key={item}>{item}</option>)}</select></div>{recommendationOpen && <div className="recommendation-box"><label className="search-label">STATIC BEST MATCHES</label><form className="search-row" onSubmit={submitRecommendation}><Sparkles size={18} color="#12645b" style={{ position: 'absolute', margin: '14px' }} /><div className="search-input" style={{ paddingLeft: 44, color: 'var(--muted)' }}>Rank candidates by profile strength and screening data</div><button className="search-button" type="submit">{loading && recommendations.length === 0 ? 'Ranking...' : 'Show best matches'}</button></form></div>}{uploadMessage && <div className="inline-message">{uploadMessage}{uploadId && <span className="upload-actions"><button onClick={() => decideUpload('approve')}>Approve</button><button onClick={() => decideUpload('reject')}>Reject</button></span>}</div>}</section>
      <div className="workspace"><section><div className="results-head"><h2>{recommendations.length ? 'Top matches' : query || Object.keys(filters).some(key => key !== 'page' && key !== 'page_size' && filters[key as keyof CandidateFilters]) ? 'Matching candidates' : 'Recent candidates'}</h2><span>{total} candidates</span></div>{error ? <div className="empty error-state">{error}</div> : loading ? <div className="empty">Ranking candidates locally...</div> : results.length ? results.map((candidate, index) => <CandidateCard key={candidate.id} candidate={candidate} rank={recommendations[index]?.rank} breakdown={recommendations[index]?.score_breakdown} explanation={recommendations[index]?.explanation} onOpen={openCandidate} />) : <div className="empty">No candidates match these requirements.</div>}<div className="pagination"><button aria-label="Previous page" disabled={hydrated && (page <= 1 || loading || recommendations.length > 0)} onClick={() => { const next = { ...filters, page: page - 1 }; setFilters(next); loadCandidates(next); }}><ChevronLeft size={16} /></button><span>Page {page} of {Math.max(1, Math.ceil(total / (filters.page_size || 20)))}</span><button aria-label="Next page" disabled={hydrated && (page >= Math.ceil(total / (filters.page_size || 20)) || loading || recommendations.length > 0)} onClick={() => { const next = { ...filters, page: page + 1 }; setFilters(next); loadCandidates(next); }}><ChevronRight size={16} /></button></div></section><aside className="rail"><h3>Candidate landscape</h3><div className="eyebrow">Top industries</div>{topIndustries.length ? topIndustries.map(([label, count]) => <Bar key={label} label={label} count={count} max={Math.max(...topIndustries.map(item => item[1]))} />) : <p style={{ fontSize: 12, color: 'var(--muted)' }}>Import the master workbook to populate insights.</p>}</aside></div>
    </main>{selected && <Profile candidate={selected} onClose={() => setSelected(null)} />}</div>;
}
function Metric({ label, value, accent }: { label: string; value: string; accent: string }) { return <div className="metric"><div className="metric-label">{label}</div><div className="metric-value">{value}</div><div className="metric-accent">{accent}</div></div>; }
function Bar({ label, count, max }: { label: string; count: number; max: number }) { return <div className="bar-item"><div className="bar-label"><span>{label}</span><span>{count}</span></div><div className="bar"><i style={{ width: `${Math.round(count / max * 100)}%` }} /></div></div>; }
function CandidateCard({ candidate, rank, breakdown, explanation, onOpen }: { candidate: Candidate; rank?: number; breakdown?: Record<string, number>; explanation?: string; onOpen: (id: string) => void }) { return <article className="candidate" onClick={() => onOpen(candidate.id)}><div><h3>{rank ? `#${rank} ` : ''}{candidate.name}</h3><div className="candidate-role">{candidate.current_position || 'Candidate'} {candidate.current_company && `at ${candidate.current_company}`}</div><div className="meta"><span>{candidate.city || 'Location not listed'}</span><span>{candidate.experience_years ?? '—'} yrs experience</span><span>{candidate.expected_salary ? `${(candidate.expected_salary / 100000).toFixed(1)} LPA expected` : 'Salary not listed'}</span><span>{candidate.notice_period_days ?? '—'}d notice</span></div><div className="skills">{candidate.skills.slice(0, 6).map(skill => <span className="skill" key={skill}>{skill}</span>)}</div></div><div className="score"><strong>{candidate.suitability_score ?? '—'}</strong><small>Suitability</small></div><div className="reasons">{breakdown && Object.entries(breakdown).map(([key, value]) => <span className="reason" key={key}>{key}: {value}%</span>)}{candidate.score_reasons.map(reason => <span className="reason" key={reason}>{reason}</span>)}{candidate.score_gaps.map(gap => <span className="gap" key={gap}>{gap}</span>)}{explanation && <span className="reason">{explanation}</span>}<ChevronRight size={15} style={{ marginLeft: 'auto' }} /></div></article>; }
function Profile({ candidate, onClose }: { candidate: Candidate; onClose: () => void }) { return <div className="profile-backdrop" onClick={onClose}><aside className="profile" onClick={event => event.stopPropagation()}><button className="close" aria-label="Close profile" onClick={onClose}><X size={18} /></button><div className="eyebrow">Candidate profile</div><h2>{candidate.name}</h2><div className="candidate-role">{candidate.current_position || 'Candidate'} {candidate.current_company && `at ${candidate.current_company}`}</div><div className="profile-grid"><Info label="Location" value={candidate.city} /><Info label="Experience" value={candidate.experience_years ? `${candidate.experience_years} years` : undefined} /><Info label="Email" value={candidate.email} /><Info label="Phone" value={candidate.phone} /><Info label="Industry" value={candidate.industry} /><Info label="Notice" value={candidate.notice_period_days ? `${candidate.notice_period_days} days` : undefined} /></div><h3>Skills</h3><div className="skills">{candidate.skills.map(skill => <span className="skill" key={skill}>{skill}</span>)}</div><h3>Education</h3><p>{candidate.education.length ? candidate.education.join(', ') : 'Not listed'}</p></aside></div>; }
function Info({ label, value }: { label: string; value?: string }) { return <div><small>{label}</small><strong>{value || 'Not listed'}</strong></div>; }
